modLoader="javafml"
loaderVersion="[43,)"
license="LGPL-3.0-only"
[[mods]]
modId="oculus"
version="${version}"
displayName="Oculus"
displayURL="https://github.com/TomatoPuddin/Oculus"
logoFile="oculus-logo.png"
authors="coderbot, IMS212, Justsnoopy30, FoundationGames, TomatoPuddin"
description='''
Unofficial Fork of "Iris", made to work with FML.
Temp fork with support for DH.
'''

[[dependencies.oculus]]
modId="forge"
mandatory=true
versionRange="[43.1.58,)"
side="BOTH"

[mods."sodium:options"]
"mixin.features.sky"=false